### ISSUE TITLE
BlueSolar D1: Not subscribing to any services

### ISSUE THREAD

**Issue by fabrees** [danielfett/bluebattery.py#4]
Currently the blue battery python script will resolve the following service:
GATT CHARACTERISTIC "4B616912-40bd-428b-bf06-698e5e422cd9" "BC"

My BlueSolar D1 only sent the following services:

> DEBUG:Device 34:15:13:e5:b8:4e:Not subscribing to 4b616914-40bd-428b-bf06-698e5e422cd9.
> DEBUG:Device 34:15:13:e5:b8:4e:Not subscribing to 4b616911-40bd-428b-bf06-698e5e422cd9.
> DEBUG:Device 34:15:13:e5:b8:4e:Not subscribing to 4b616910-40bd-428b-bf06-698e5e422cd9.
> DEBUG:Device 34:15:13:e5:b8:4e:Not subscribing to 4b616907-40bd-428b-bf06-698e5e422cd9.
> DEBUG:Device 34:15:13:e5:b8:4e:Not subscribing to 4b616901-40bd-428b-bf06-698e5e422cd9.

I assume that the characteristic 4b616914 is not described fully.
Unfortunatly the forum entry https://www.blue-battery.com/forum/bluebattery/bluetoothprotokoll does not help too.

**Comment by kscheff** [comment]
See issue #3 you need to cache the descriptor first.

**Comment by fabrees** [comment]
Caching the descriptor does not help. The GUID [..]12-[..] of the "BC" service is not offered by the BlueSolar D1 somehow.

**Comment by kscheff** [comment]
When the device boots up not all descriptors are available. The devices waits 5 seconds before the additional features are listed. When you form a Bluetooth connection within this first 5 seconds, the device will not start up further and consequently the additional descriptor UUIDs will not be showing. In order to successfully use the device, let the device run for 5 seconds before any connection is established. The device starts to blink its LED when it is ready. 

In case you wonder, the initial 5 seconds delay is used for firmware update purposes.

**Comment by danielfett** [comment]
I assume that this has been solved with the new version I just published. I should be resilient against non-existing descriptors.
